# Generated by Django 6.0 on 2025-12-18 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo_json', models.FileField(blank=True, help_text='Arquivo de molde (.mld preferencialmente ou .json)', null=True, upload_to='moldes/', validators=[django.core.validators.FileExtensionValidator(['mld', 'json'])])),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='moldes/thumbs/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoldeDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=200)),
                ('tipo_geom', models.CharField(max_length=50)),
                ('area_base_mm2', models.FloatField(default=0.0, help_text='Área líquida da peça')),
                ('largura_mm', models.FloatField(default=0.0, help_text='Largura do bounding box (mm)')),
                ('altura_mm', models.FloatField(default=0.0, help_text='Altura do bounding box (mm)')),
                ('qtd_padrao', models.IntegerField(default=1)),
                ('rotacao_fixa', models.BooleanField(default=False, help_text='Se marcado, a peça não pode ser rotacionada (respeitar fio)')),
                ('orientacao_fio', models.CharField(blank=True, help_text='Orientação do fio (ex: vertical, horizontal)', max_length=50, null=True)),
                ('geometria_json', models.JSONField(help_text='Dados completos da geometria para desenho')),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='molds.molde')),
            ],
        ),
    ]
