# Generated by Django 6.0 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_PRODUCAO', 'Em Produção'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('quantidade_total', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade deste item de pedido atendida nesta OP')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_origem', to='production.ordemproducao')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='sales.pedidoitem')),
            ],
        ),
    ]
