# Generated by Django 6.0 on 2025-12-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(blank=True, max_length=50, null=True)),
                ('topico_mqtt', models.CharField(help_text='Tópico MQTT que esta máquina publica (ex: maquina/001/status)', max_length=200)),
                ('status_atual', models.CharField(choices=[('LIGADO', 'Ligado'), ('DESLIGADO', 'Desligado')], default='DESLIGADO', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('op_atual', models.ForeignKey(blank=True, help_text='Qual OP esta máquina está trabalhando no momento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_alocadas', to='production.ordemproducao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.FloatField(default=0.0)),
                ('finalizado', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='production.maquina')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='production.ordemproducao')),
            ],
        ),
    ]
