# Generated by Django 6.0 on 2025-12-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_maquina_registroproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='maquinas',
            field=models.ManyToManyField(blank=True, help_text='Máquinas planejadas para esta OP', related_name='ops', to='production.maquina'),
        ),
    ]
