# Generated by Django 6.0 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada ao Fornecedor'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('pedidos', models.ManyToManyField(blank=True, help_text='Pedidos contemplados nesta ordem de compra', related_name='ordens_compra', to='sales.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.FloatField(default=0.0, help_text='Soma da necessidade real dos pedidos')),
                ('quantidade_estoque_na_epoca', models.FloatField(default=0.0, help_text='Quanto havia em estoque no momento da geração')),
                ('quantidade_comprar', models.FloatField(default=0.0, help_text='Quantidade sugerida para compra (Necessária - Estoque)')),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('ordem_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='purchases.ordemcompra')),
            ],
        ),
    ]
