# Generated by Django 6.0 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('hex_code', models.CharField(default='#FFFFFF', help_text='Cor hexadecimal para visualização', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('unidade', models.CharField(help_text='Ex: mt, un, kg, par', max_length=50)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço atual de referência (Última Compra)', max_digits=10)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0.0, help_text='Média ponderada do estoque', max_digits=10)),
                ('estoque_atual', models.FloatField(default=0.0)),
                ('eh_tecido', models.BooleanField(default=False, help_text='Marque se este material for usado para corte (Tecido)')),
                ('largura_padrao_mm', models.IntegerField(blank=True, default=1500, help_text='Apenas para tecidos', null=True)),
                ('tem_cor', models.BooleanField(default=False, help_text='Se marcado, exige escolha de cor na Variante')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade', models.FloatField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('cor', models.ForeignKey(blank=True, help_text='Cor do material que está entrando', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0.0)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='inventory.material')),
            ],
            options={
                'unique_together': {('material', 'cor')},
            },
        ),
    ]
