# Generated by Django 6.0 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('molds', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clients.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE_CADASTRO', 'Pendente Cadastro Técnico'), ('LIBERADO_PRODUCAO', 'Liberado para Produção'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDO', 'Concluído')], default='PENDENTE_CADASTRO', max_length=30)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('molde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='molds.molde')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.pedido')),
                ('produto', models.ForeignKey(blank=True, help_text='SKU selecionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.cor')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('molde_peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molds.moldedetalhe')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='sales.pedidoitem')),
            ],
            options={
                'unique_together': {('pedido_item', 'molde_peca')},
            },
        ),
    ]
