# Generated by Django 6.0 on 2025-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='status',
            field=models.CharField(choices=[('PENDENTE_CADASTRO', 'Pendente Cadastro Técnico'), ('LIBERADO_PRODUCAO', 'Liberado para Produção'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE_CADASTRO', max_length=30),
        ),
    ]
