# Generated by Django 6.0 on 2025-12-18 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('molds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='products.ordemservicotecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('eh_padrao', models.BooleanField(default=False, help_text='Indica se é a Referência Padrão do Molde.')),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço base ou preço do SKU', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cor', models.ForeignKey(blank=True, help_text='Cor global do produto (opcional, prioriza cor por peça)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cor')),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='molds.molde')),
                ('parent', models.ForeignKey(blank=True, help_text='Se preenchido, este produto é uma VARIANTE/SKU.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='products.produto')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservicotecnica',
            name='produto_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_origem', to='products.produto'),
        ),
        migrations.CreateModel(
            name='ItensMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0.0)),
                ('tipo', models.CharField(choices=[('tecido_padrao', 'Tecido Padrão'), ('insumo', 'Insumo / Aviamento')], default='insumo', max_length=20)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('molde_detalhe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='molds.moldedetalhe')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_material', to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.FloatField(default=0.0)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0.0)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.cor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='products.produto')),
            ],
        ),
    ]
