# Generated by Django 6.0 on 2025-12-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='pedido_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='os_tecnica', to='sales.pedidoitem'),
        ),
    ]
