# Generated by Django 6.0 on 2025-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ordemservicoitem_pedido_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
    ]
